SELECT it.ITEM_ID AS ITEM_ID, ii.ITEM_NAME AS ITEM_NAME, ii.RARITY AS RARITY
FROM ITEM_TREE it 
JOIN ITEM_INFO ii ON it.ITEM_ID = ii.ITEM_ID
WHERE it.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID
                        FROM ITEM_TREE
                        WHERE PARENT_ITEM_ID IS NOT NULL
                        GROUP BY PARENT_ITEM_ID)
ORDER BY it.ITEM_ID DESC



