
SELECT YEAR(os.SALES_DATE) AS YEAR, MONTH(os.SALES_DATE) AS MONTH, ui.GENDER, COUNT(DISTINCT os.USER_ID) AS USERS
FROM ONLINE_SALE os
JOIN USER_INFO ui ON os.USER_ID = ui.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER
ORDER BY YEAR(os.SALES_DATE) ASC, MONTH(os.SALES_DATE) ASC, ui.GENDER ASC