SELECT COUNT(fi.ID) AS FISH_COUNT, fni.FISH_NAME AS FISH_NAME
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
GROUP BY fi.FISH_TYPE, fni.FISH_NAME
ORDER BY COUNT(fi.ID) DESC;
