SELECT original.CAR_ID AS CAR_ID, 
    CASE WHEN temp.CAR_ID IS NULL THEN "대여 가능"
    ELSE "대여중" END AS "AVAILABILITY"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY original
LEFT JOIN(  SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE DATE("2022-10-16") BETWEEN START_DATE AND END_DATE
            GROUP BY CAR_ID
         ) temp ON original.CAR_ID = temp.CAR_ID
GROUP BY original.CAR_ID
ORDER BY original.CAR_ID DESC;