SELECT ugb.WRITER_ID AS USER_ID, ugu.NICKNAME AS NICKNAME, SUM(ugb.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD ugb
JOIN USED_GOODS_USER ugu ON ugb.WRITER_ID = ugu.USER_ID
WHERE ugb.STATUS = "DONE" 
GROUP BY WRITER_ID
HAVING SUM(ugb.PRICE) >= 700000
ORDER BY SUM(ugb.PRICE) ASC;