SELECT DISTINCT crcc.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
JOIN CAR_RENTAL_COMPANY_CAR crcc ON crcrh.CAR_ID = crcc.CAR_ID
WHERE crcc.CAR_TYPE = "세단" AND YEAR(crcrh.START_DATE) = 2022 AND MONTH(crcrh.START_DATE) = 10
ORDER BY crcc.CAR_ID DESC;