# SELECT EMP_NO
# FROM HR_GRADE
# WHERE 
WITH YEAR_GRADE AS (SELECT EMP_NO, SUM(SCORE) AS SCORE
                    FROM HR_GRADE
                    WHERE YEAR = 2022
                    GROUP BY EMP_NO)
                    
SELECT yg.SCORE AS SCORE, yg.EMP_NO AS EMP_NO, he.EMP_NAME AS EMP_NAME, he.POSITION AS POSITION, he.EMAIL AS EMAIL
FROM YEAR_GRADE yg
JOIN HR_EMPLOYEES he ON yg.EMP_NO = he.EMP_NO
WHERE yg.SCORE = (SELECT MAX(SCORE) FROM YEAR_GRADE);