WITH TEMP_FISH_INFO AS (
    SELECT ID, FISH_TYPE, 
        CASE WHEN LENGTH <= 10 OR LENGTH IS NULL THEN 10
        ELSE LENGTH END AS LENGTH
    FROM FISH_INFO)

SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM TEMP_FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE
